apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: backend-
spec:
  serviceAccountName: build-bot
  params:
  - name: app-name
    value: backend
  - name: source-repo
    value: https://github.com/davidbieder/fullstack-backend-with-database
  - name: image-repo
    value: quay.io/davidbieder/fullstack-backend-with-database
  pipelineRef:
    name: nodejs
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
        - ReadWriteOnce
  - name: gitops-repository
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
  - name: git-credentials
    secret:
      secretName: git-credentials